name: CD
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm
      - name: Build
        run: pnpm build
      - name: upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: personal_website
          path: build
  deploy-release:
    needs: [build-release]
    runs-on: ubuntu-latest
    steps:
      - name: download website
        uses: actions/download-artifact@v5
        with:
          name: personal_website
          path: build
      - name: scp
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SSH_REMOTE_HOST }}
          username: ${{ secrets.SSH_UNAME}}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: build/**
          target: personal_website
      - name: deploy to page
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_REMOTE_HOST }}
          username: ${{ secrets.SSH_UNAME}}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd personal_website
            rm previous
            mv prod previous
            mv build prod
