name: CI

on:
  push:
    branches:
      - main
      - refs/tags/*
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm
      # - name: Audit
      # run: pnpm audit
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
          continue_on_error: false
      - name: Build Project
        run: pnpm build
      # add tests here
