name: CI

on:
  push:
    branches:
      - main
      - refs/tags/*
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm
      # - name: Audit
      # run: pnpm audit
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
          continue_on_error: false
      - name: Build Project
        run: pnpm build
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: build/
          name: github-pages
  push_to_pages:
    if: github.event_name == 'pull_request'
    needs: [check]
    runs-on: ubuntu-latest
    steps:
      - name: deploy to gh-pages for review
        uses: actions/upload-pages-artifact@v4.0.0
        id: deployment
        with:
            path: artifact
  publish:
    if: github.ref_name == 'main' && github.ref_type == 'branch'
    needs: [check]
    runs-on: ubuntu-latest
    environment: publish
    steps:
      - name: Disable GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_NAME: ${{ github.repository }}
        run: |
          echo "Disabling GitHub Pages for repository $REPO_NAME"
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${REPO_NAME}/pages
      - name: create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm dlx semantic-release
