name: CI

on:
  push:
    branches:
      - main
      - refs/tags/*
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm
      # - name: Audit
      # run: pnpm audit
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
          continue_on_error: false
      - name: Build Project
        run: pnpm build
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: build/
          name: github-pages
  push_to_pages:
    if: github.event_name == 'pull_request'
    needs: [check]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
        with:
          preview: true
  publish:
    if: github.ref_name == 'main' && github.ref_type == 'branch'
    needs: [check]
    runs-on: ubuntu-latest
    environment: publish
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm
      - name: create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm dlx semantic-release
